language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: linux
      compiler: arm-linux-gnueabi-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabi
            - libc-dev-armel-cross
      env: CHOST=arm-linux-gnueabi
    - os: osx
      osx_image: xcode9.4
script:
- make LZMA=0
- make clean
- git clone https://github.com/sisong/lzma.git ../lzma
- make DIR_DIFF=0
- make clean
- make
- make clean
- git clone https://github.com/sisong/libmd5.git ../libmd5
- make SYNC=1
- make clean
- cd ../lzma
- git checkout -b pthread origin/pthread
- cd ../HDiffPatch
- make MT=1 MD5=1 SYNC=1 
- if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme hdiffz -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme hpatchz -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme unitTest -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/sync_server.xcworkspace -scheme sync_server -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/sync_client_test.xcworkspace -scheme sync_client_test -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi

